# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore Titius.Labs.FarmersCorner.csproj
COPY . .
WORKDIR /src
RUN dotnet build Titius.Labs.FarmersCorner.csproj -c Release -p /app/build

FROM build AS publish
RUN dotnet publish Titius.Labs.FarmersCorner.csproj -c Release -o /app/publish /p:UseAppHost=false

# final stage/image
FROM base AS final
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Titius.Labs.FarmersCorner.dll"]